# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-03 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
