# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-04 23:20
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('flows', '0002_auto_20180803_0301'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowShare',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('editor', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='flow',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False),
        ),
        migrations.AddField(
            model_name='flow',
            name='icon',
            field=models.CharField(blank=True, default='bulllet', max_length=50),
        ),
        migrations.AddField(
            model_name='flowshare',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='flows.Flow'),
        ),
        migrations.AddField(
            model_name='flowshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to=settings.AUTH_USER_MODEL),
        ),
    ]
